import sys
import os
import time
import threading
import subprocess

# Add parent dir to path to import engine
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from engine import HyprlandEngine

def start_server():
    """Starts the Flask server in a separate thread (or process for robustness)"""
    # For robust demo, we'll run it as a subprocess to keep it clean
    # But for easy debug output, thread is simpler. 
    # Let's use subprocess to ensure it kills cleanly if we kill this script.
    
    # Actually, if we run it as subprocess, we need to ensure we kill it.
    server_path = os.path.join(os.path.dirname(__file__), "server.py")
    cmd = [sys.executable, server_path]
    return subprocess.Popen(cmd)

def main():
    engine = HyprlandEngine(target_workspace=2)
    game_patterns = ["BoggleBoard", "BoggleTimer", "BoggleLeaderboard", "BoggleJoin", "BoggleController"]
    
    server_proc = None
    
    try:
        # 1. Start Game Server
        print("Starting Boggle Server...")
        server_proc = start_server()
        time.sleep(2) # Give Flask a moment
        
        # 2. Clean Slate
        engine.clean_slate(game_patterns)
        
        # 3. Setup Layout
        # engine.switch_to_workspace() # DISABLED per user request
        engine.set_background(color="#1e1e2e") 
        engine.set_animations() # Enable bouncy animations
        
        print("Spawning Boggle Windows (Ghostty)...")
        
        # We use Ghostty for the "Terminal Game" aesthetic
        term_cmd = "ghostty --config=../ghostty_game.conf -e python tui.py"
        
        # Absolute path to tui.py needed for robustness
        tui_path = os.path.join(os.path.dirname(__file__), "tui.py")
        # Use absolute path instead of relative path manipulation that might be fragile
        config_path = os.path.expanduser("~/code/games/ghostty_game.conf")
        
        # Explicitly quote command for ghostty if needed, but ghostty handles spaces in args if quoted in shell
        # Actually, let's verify if 'python' is in path
        python_cmd = sys.executable
        
        def get_cmd(mode, font_size=20, title="BoggleApp"):
            # Ensure proper quoting if paths have spaces, though our paths don't
            # The title is crucial for the engine to identify the window if we don't use class
            # NOTE: Ghostty 1.0 uses --font-size=N directly or configuration overrides
            # -o might not be valid for font-size directly in all versions?
            # Let's try explicit flag if supported or config override syntax
            # The help says --key=value for config keys. font-size is a config key.
            return f"ghostty --config-file={config_path} --title={title} --font-size={font_size} -e {python_cmd} {tui_path} {mode}"

        # Layout based on 2048x1080 resolution (Logical)
        # Content Width = 1900
        # Margin = (2048 - 1900) / 2 = 74
        
        start_x = 74
        col_2_x = start_x + 1000 + 30 # 1104
        
        # Vertical Spacing for Sidebar (Total Height ~1000px available)
        # Timer: 250px
        # Leaderboard: 500px
        # Join: 230px
        # Gap: 10px
        # Total: 250 + 10 + 500 + 10 + 230 = 1000 (Fits exactly in 20-1020 range)
        
        # Use localhost for internal windows (faster, reliable)
        # But display the LAN IP for external players
        internal_host = "127.0.0.1"
        external_host = "192.168.1.31" 
        
        windows = [
            {
                # Main Board (Left)
                "command": f"chromium --app=http://{internal_host}:8080/view/board",
                # Matches class generated by chromium for localhost
                "name_pattern": f"chrome-{internal_host}__view_board-Default",
                "x": start_x, "y": 20, 
                "width": 1000, "height": 1000,
                "is_class": True 
            },
            {
                # Timer (Top Right)
                "command": get_cmd('timer', 60, "BoggleTimer"),
                "name_pattern": "BoggleTimer",
                "x": col_2_x, "y": 20, 
                "width": 850, "height": 250
            },
            {
                # Leaderboard (Middle Right)
                "command": get_cmd('leaderboard', 18, "BoggleLeaderboard"),
                "name_pattern": "BoggleLeaderboard",
                "x": col_2_x, "y": 280, 
                "width": 850, "height": 450 
            },
            {
                # Join Info (Bottom Right)
                "command": f"chromium --app=http://{internal_host}:8080/view/join",
                "name_pattern": f"chrome-{internal_host}__view_join-Default",
                "x": col_2_x, "y": 740, 
                "width": 850, "height": 300, 
                "is_class": True 
            }
        ]

        
        engine.spawn_batch(windows)
        
        print("Boggle Game Running on Workspace 2.")

        print(f"Server at http://{external_host}:8080")
        print("Press Ctrl+C to stop.")
        
        while True:
            time.sleep(1)
            
    except KeyboardInterrupt:
        print("\nStopping Boggle...")
    except Exception as e:
        print(f"Error: {e}")
    finally:
        if server_proc:
            server_proc.terminate()
        engine.cleanup()
        engine.clean_slate(game_patterns)

if __name__ == "__main__":
    main()
